# Generated by Django 3.0.1 on 2020-01-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="verification_code",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
